checks:
    php: true

before_commands:
    - git clone https://github.com/AOEpeople/codingstandards.git

tools:

    #external_code_coverage:
    #    timeout: 700
    #    runs: 1

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: custom
            ruleset: codingstandards/ide/standard/ruleset.xml

    php_cs_fixer:
        enabled: true

    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant:  false

    php_mess_detector:
        enabled: true
        config:
            ruleset: codingstandards/messdetector/standard/ruleset.xml

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true
